# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification – Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

version = 1

[[annotations]]
path = [
    "/subject-avatar-icon.jpg"
]
SPDX-FileCopyrightText = '1970 AI generated image, no copyright. <http://www.wtfpl.net/>'
SPDX-License-Identifier = 'WTFPL'
